### PR TITLE
Use LinkedHashMap where struct key order matters.

### PR DESCRIPTION
**Pull request by elpete**
This should fix the remaining Travis CI failures.

### CODE REVIEW

**Comment by elpete** [comment]
Ignore the Lucee versions thing. Sorry.

**Comment by russplaysguitar** [comment]
Any idea why the lucee 5 tests report this error? 

```
[mxunitoutputtask]     invalid syntax at /home/travis/build/russplaysguitar/UnderscoreCF/Underscore.cfc:221 ...
```

**Comment by elpete** [comment]
I think it has to do with running an older version of Lucee 5. I've been looking for a new link to update the build but I haven't had much luck yet.

**Comment by elpete** [comment]
Closing this as it has been sitting here for a long time.

**Pull request closed without merging**
